site:
  title: "Model Context Protocol (MCP) for Ansible Automation Platform"
  start_page: aap-mcp-server::index.adoc

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true

content:
  sources:
  - url: ./

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
